[tool.poetry]
name = "guess-num-game"
version = "0.1.0"
description = ""
authors = ["luojiejun <ljj@knd.com.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.40.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
